<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Recent
 */
?>

<?php
$_postCollection = $block->getPostCollection();
//$_post = $this->getPost();
//$_postUrl = $_post->getPostUrl();
//$_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<?php if ($_postCollection->count()) { ?>
    <div class="widget block block-recent-posts" data-bind="scope: 'recemt-posts'">
        <div class="block-title">
            <strong><?php echo __('Recent Posts') ?></strong>
        </div>
        <div class="block-content">
            <?php foreach ($_postCollection as $_post) { ?>
                <div class="item">
                    <div class="recent-posts-image">
                        <div class="widget-image-wrap" style="background-image: url('<?php echo $_post->getFeaturedImage() ?>');">
                        </div>
                    </div>
                    <div class="recent-posts-link">
                        <a class="post-item-link"
                           href="<?php echo $_post->getPostUrl() ?>">
                            <?php echo $block->escapeHtml($_post->getTitle()) ?>
                        </a>
                        <p></p>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
<?php } ?>