<?php

use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <div data-block="product_list" data-bind="scope: 'product_list'" class="products wrapper <?php /* @escapeNotVerified */ echo $block->getMode(); ?> products-<?php /* @escapeNotVerified */ echo $block->getMode(); ?>">
        <ol class="products list items product-items">
            <?php /*
                Note: the lack of any whitespace between the knockout foreach loop
                and the <li></li> tag below is intentional. Magento's luma theme
                displays each product as an inline-block with a percentage of the
                container width, so any whitespace between the closing </li> and the
                following <li> will break the grid layout. Magento get around this
                with some $iterator nonsense, and we fix it by omitting any whitespace
                at the start and end of the ko template.
            */ ?>
            <!-- ko foreach: state.products --><li class="item product product-item" data-bind="visible: true" style="display: none;">
                <div class="product-item-info" data-container="product-grid">
                    <a data-bind="{attr: {href: url}, html: image}" class="product photo product-item-photo" tabindex="-1"></a>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <a class="product-item-link" data-bind="{attr: {href: url}, html: name}"></a>
                        </strong>
                        <div class="product-item-inner">
                            <div class="product description product-item-description">
                                <div data-bind="html: description"></div>
                            </div>
                        </div>
                        <div data-bind="html: price"></div>
                        <span class="price-vat">inkl. MwSt. | zzgl. Versand</span>
                        <div data-bind="html: details"></div>
                        <a data-bind="attr: {href: url, title: name_stripped}" class="btn-custom orange-btn"><span><?php /* @escapeNotVerified */ echo __('Details') ?></span></a>
                    </div>
                </div>
            </li><!-- /ko -->
        </ol>
        <div class="product-list-actions" data-bind="blockLoader: state.isFetching">
            <button class="action secondary" data-bind="{visible: state.isMoreAvailable() && !state.isFetching(), click: loadMore}" style="display: none"><?php echo __('View More') ?></button>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "[data-block='product_list']": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "product_list": {
                            "component": "Meanbee_InfiniteScroll/js/view/product_list",
                            "state": <?php echo $this->helper(\Meanbee\InfiniteScroll\Helper\Data::class)->getProductListJson($block) ?: "[]" ?>
                        }
                    }
                }
            }
        }
    </script>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

<script type="text/javascript">
    require(["jquery","matchheight"], function ($) {
        // Matchheight
        $('.widget.block .product-item .product-item-details').matchHeight(
            {
                byRow: true,
                property: 'height',
                target: null,
                remove: false
            }
        );
    });
</script>
