<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Register $block */
?>
<?= $block->getChildHtml('form_fields_before') ?>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.register.extra') ?>
<div class="create-account">
    <form class="form create account form-create-account" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
        <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
        <h1><?= $block->escapeHtml(__('Registrieren')) ?></h1>
        <fieldset class="fieldset create info">
            <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
            <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
            <div class="custom title-input">
                <label class="label">
                    <span><?= $block->escapeHtml(__('Anrede')) ?></span>
                </label>
                <div class="field custom">
                    <input type="radio" id="titleMrs" name="title" value="Mrs" class="input-text">
                    <label class="label" for="titleMrs">
                        <span><?= $block->escapeHtml(__('Frau')) ?></span>
                    </label>
                </div>
                <div class="field custom">
                    <input type="radio" checked="checked" id="titleSir" name="title" value="Sir" class="input-text">
                    <label class="label" for="titleSir">
                        <span><?= $block->escapeHtml(__('Her')) ?></span>
                    </label>
                </div>
            </div>
            <?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>

            <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <?= $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
            <?php endif ?>

            <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <?= $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
            <?php endif ?>

            <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <?= $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
            <?php endif ?>

            <div class="field required">
                <label for="email_address" class="label"><span><?= $block->escapeHtml(__('E-Mail Adresse')) ?></span></label>
                <div class="control">
                    <input type="email" name="email" autocomplete="email" id="email_address" value="<?= $block->escapeHtmlAttr($block->getFormData()->getEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
                </div>
            </div>
                <input type="hidden" name="create_address" value="1" />

                <?php $_company = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Company') ?>
                <?php if ($_company->isEnabled()): ?>
                    <?= $_company->setCompany($block->getFormData()->getCompany())->toHtml() ?>
                <?php endif ?>

                <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
                <?php if ($addressAttributes): ?>
                    <?php $addressAttributes->setEntityType('customer_address'); ?>
                    <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                    <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                    <?= $addressAttributes->setShowContainer(false)->toHtml() ?>
                <?php endif;?>
                <input type="hidden" name="default_billing" value="1">
                <input type="hidden" name="default_shipping" value="1">

            <div class="custom">
                <div class="field custom">
                    <input type="radio" checked="checked" id="commercial-customer" name="customer" value="Commercial customer" class="input-text">
                    <label class="label" for="commercial-customer">
                        <span><?= $block->escapeHtml(__('Gewerbekunde')) ?></span>
                    </label>
                </div>
                <div class="field custom">
                    <input type="radio" id="private-customer" name="customer" value="Private customer" class="input-text">
                    <label class="label" for="private-customer">
                        <span><?= $block->escapeHtml(__('Privatkunde')) ?></span>
                    </label>
                </div>
            </div>
            <div class="field password required">
                <label for="password" class="label"><span><?= $block->escapeHtml(__('Passwort')) ?></span></label>
                <div class="control">
                    <input type="password" name="password" id="password"
                           title="<?= $block->escapeHtmlAttr(__('Passwort')) ?>"
                           class="input-text"
                           data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                           data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                           data-validate="{required:true, 'validate-customer-password':true}"
                           autocomplete="off">
                    <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                        <div id="password-strength-meter" class="password-strength-meter">
                            <?= $block->escapeHtml(__('Password Strength')) ?>:
                            <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                <?= $block->escapeHtml(__('No Password')) ?>
                            </span>
                        </div>
                    </div>
                </div>

            </div>
            <div class="field confirmation required">
                <label for="password-confirmation" class="label"><span><?= $block->escapeHtml(__('Passwort wiederholen')) ?></span></label>
                <div class="control">
                    <input type="password" name="password_confirmation" title="<?= $block->escapeHtmlAttr(__('Passwort wiederholen')) ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                </div>
            </div>
            <p><?= $block->escapeHtml(__('Wenn Sie ein Gewerbe Kunde sind, bitten wir Sie nach der Registrierung uns Ihren Gewerbenachweis per E-Mail zu schicken: b2b@luis-shop.de')) ?></p>
            <div class="field choice terms">
                <input type="checkbox" data-validate="{required:true}" name="terms" title="<?= $block->escapeHtmlAttr(__('Ich akzeptiere die AGB und die Datenschutzerklärung.')) ?>" value="1" id="terms" class="checkbox">
                <label for="terms" class="label">
                    <span>
                        <?= $block->escapeHtml(__('Ich akzeptiere die'));?><a href="<?php echo $block->getUrl('datenschutz');?>" target="_blank"> <?= $block->escapeHtml(__('AGB und die Datenschutzerklärung'));?></a>.*
                    </span>
                </label>
            </div>
            <?php if ($block->isNewsletterEnabled()): ?>
                <div class="field choice newsletter">
                    <input type="checkbox" name="is_subscribed" title="<?= $block->escapeHtmlAttr(__('Ich möchte per E-Mail Neuigkeiten von LUIS erhalten.')) ?>" value="1" id="is_subscribed"<?php if ($block->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox">
                    <label for="is_subscribed" class="label"><span><?= $block->escapeHtml(__('Ich möchte per E-Mail Neuigkeiten von LUIS erhalten.')) ?></span></label>
                </div>
                <?php /* Extensions placeholder */ ?>
                <?= $block->getChildHtml('customer.form.register.newsletter') ?>
            <?php endif ?>
            <?= $block->getChildHtml('form_additional_info') ?>
        </fieldset>
        <button type="submit" class="action submit btn-custom orange-btn" title="<?= $block->escapeHtmlAttr(__('Registrieren')) ?>"><span><?= $block->escapeHtml(__('Register')) ?></span></button>

    </form>
</div>
<script>
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#form-validate');
    var ignore = <?= /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;

    dataForm.mage('validation', {
    <?php if ($_dob->isEnabled()): ?>
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'
    <?php else: ?>
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    <?php endif ?>
    }).find('input:text').attr('autocomplete', 'off');

});
</script>
<?php if ($block->getShowAddressFields()): ?>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= (int) $block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        }
    }
</script>
