<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()): ?>
    <div class="additional-attributes-wrapper table-wrapper">
        <div class="data table additional-attributes" id="product-attribute-specs-table">
            <?php foreach ($_additional as $_data): ?>
                <div class="product-attr">
                    <img src='<?php echo $this->getViewFileUrl('images/icons/arrow.svg'); ?>' alt="Demo">
                    <span class="col label"><?= $block->escapeHtml(__($_data['label'])) ?>:</span>
                    <span class="col data"><?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></span>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif;?>
