<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<div class="cart item">
    <div class="item-info">
        <div data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
            <?php if ($block->hasProductUrl()):?>
                <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"
                   title="<?= $block->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else:?>
                <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()):?>
                </a>
            <?php else: ?>
                </span>
            <?php endif; ?>
        </div>

        <?php if ($canApplyMsrp): ?>
            <div class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= /* @escapeNotVerified */ __('See price before order confirmation.') ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?= /* @escapeNotVerified */ ($helpLinkId) ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?= /* @escapeNotVerified */ $helpLinkId ?>","productName": "<?= /* @escapeNotVerified */ $product->getName() ?>","showAddToCart": false}}'>
                        <span><?= /* @escapeNotVerified */ __("What's this?") ?></span>
                    </a>
                </span>
            </div>
        <?php else: ?>
        <div class="product-details-wrapper">
            <div class="product-item-details">
                <h4 class="product-item-name">
                    <?php if ($block->hasProductUrl()):?>
                        <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else: ?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </h4>
                <?php if ($_options = $block->getOptionList()):?>
                    <div class="item-options">
                        <?php foreach ($_options as $_option) : ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <div><?= $block->escapeHtml($_option['label']) ?></div>
                            <div>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <?= /* @escapeNotVerified */ $_formatedOptionValue['full_view'] ?>
                                <?php else: ?>
                                    <?= /* @escapeNotVerified */ $_formatedOptionValue['value'] ?>
                                <?php endif; ?>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endif;?>
                <?php if ($messages = $block->getMessages()): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class="cart item message <?= /* @escapeNotVerified */ $message['type'] ?>"><div><?= $block->escapeHtml($message['text']) ?></div></div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock): ?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
            </div>
            <div class="item-actions">
                <div>
                    <div class="actions">
                        <?= /* @escapeNotVerified */ $block->getActions($_item) ?>
                    </div>
                </div>
            </div>
            <div class="item-sku">
                <span><?= $block->escapeHtml($product->getSku()) ?></span>
            </div>
            <div class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                    <?= $block->getUnitPriceHtml($_item) ?>
            </div>
            <?php endif; ?>
            <div class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
                <div class="field qty">
                    <label for="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty">
                        <span><?= /* @escapeNotVerified */ __('Anzahl') ?></span>
                    </label>
                    <div class="control qty">
                        <input id="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty"
                               name="cart[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]"
                               data-cart-item-id="<?= $block->escapeHtml($_item->getSku()) ?>"
                               value="<?= /* @escapeNotVerified */ $block->getQty() ?>"
                               type="number"
                               size="4"
                               title="<?= $block->escapeHtml(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="{required:true,'validate-greater-than-zero':true}"
                               data-role="cart-item-qty"/>
                    </div>
                </div>
            </div>

            <div class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
                <?php if ($canApplyMsrp): ?>
                    <span class="cart msrp subtotal">--</span>
                <?php else: ?>
                <label>Preis</label>
                    <?= $block->getRowTotalHtml($_item) ?>
                <?php endif; ?>
                <span class="price-vat">inkl. 19 % MwSt. zzgl. Versand</span>
            </div>
        </div>
    </div>
</div>
