<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Contact\Block\ContactForm $block */
?>

<h1>Message</h1>
<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="custom">
            <label class="label">
                <span><?= $block->escapeHtml(__('Title')) ?></span>
            </label>
            <div class="field custom">
                <input type="radio" id="titleMrs" name="title" value="Mrs" class="input-text">
                <label class="label" for="titleMrs">
                    <span><?= $block->escapeHtml(__('Mrs')) ?></span>
                </label>
            </div>
            <div class="field custom">
                <input type="radio" checked="checked" id="titleSir" name="title" value="Sir" class="input-text">
                <label class="label" for="titleSir">
                    <span><?= $block->escapeHtml(__('Sir')) ?></span>
                </label>
            </div>
        </div>
        <div class="field name first-name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('First name')) ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field name last-name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Last name')) ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment"><span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span></label>
            <div class="control">
                <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div>
        <input type="hidden" name="hideit" id="hideit" value="" />
        <button type="submit" title="<?= $block->escapeHtmlAttr(__('Send')) ?>" class="action submit btn-custom orange-btn">
            <span><?= $block->escapeHtml(__('Send')) ?></span>
        </button>
    </div>
</form>
