<?php $postedData = $block->getPostedValue(); ?>

<div class="column main">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('jobs-large-image')->toHtml();?>

    <?php
    if (
        in_array($block->getCurrentStore(), $block->getStores()) || // for respective store view
        in_array(0, $block->getStores()) || // for All Stores
        $block->getStores() === [] // for General Application
    ):
        if ($block->isStatusOpen()):
            if ($block->isDeadlineNotOver()):
                ?>
                <div class="application-form">
                    <h2><?php echo $block->getJobTitle(); ?></h2>
                    <script type="text/javascript" src="//platform.linkedin.com/in.js">
                        api_key: <?php echo $block->getLinkedInAPIKey() . PHP_EOL; ?>
                            scope: r_basicprofile
                        r_emailaddress
                        onLoad: onLinkedInLoad
                    </script>
                    <script type="in/Login"></script>


                    <form class="form-apply" action="<?php echo $block->getFormAction() ?>"
                          id="job-application-from"
                          method="post"
                          enctype="multipart/form-data"
                          data-mage-init='{"validation":{}}'>
                        <?php echo $block->getBlockHtml('formkey'); ?>
                        <div class="field required">
                            <div class="control">
                                <label class="label"><?= $block->escapeHtmlAttr(__('First name')) ?> <span>*</span> </label>
                                <input
                                        id="firstname"
                                        type="text"
                                        name="first_name"
                                        value="<?php echo isset($postedData['first_name']) ? $postedData['first_name'] : '' ?>"
                                        data-validate='{"required":true}'
                                        placeholder=""
                                        class="input-text">
                            </div>
                        </div>
                        <div class="field required">
                            <div class="control">
                                <label class="label"><?= $block->escapeHtmlAttr(__('Last name')) ?> <span>*</span> </label>
                                <input
                                        id="lastname"
                                        type="text"
                                        name="last_name"
                                        value="<?php echo isset($postedData['last_name']) ? $postedData['last_name'] : '' ?>"
                                        data-validate='{"required":true}'
                                        placeholder=""
                                        class="input-text">
                            </div>
                        </div>
                        <div class="field required">
                            <div class="control">
                                <label class="label"><?= $block->escapeHtmlAttr(__('Address')) ?> <span>*</span> </label>
                                <input
                                        type="text"
                                        name="address"
                                        value="<?php echo isset($postedData['address']) ? $postedData['address'] : '' ?>"
                                        data-validate='{"required":true}'
                                        placeholder=""
                                        class="input-text">
                            </div>
                        </div>
                        <div class="field required">
                            <div class="control errorStylingProp">
                                <label class="label"><?php echo $block->escapeHtmlAttr(__('Country')) ?> <span>*</span> </label>
                                <select name="country" id="country" id="country" data-validate='{"required":true}'>
                                    <option value="">-- <?php echo $block->escapeHtmlAttr(__('Select Country')) ?>--
                                    </option>
                                    <?php
                                    foreach ($block->getCountriesList() as $key => $value):
                                        if ($value['value'] === '' || $value['label'] === '') {
                                            continue;
                                        }
                                        ?>
                                        <option value="<?php echo $value['label'] ?>" <?php echo (isset($postedData['country']) && $postedData['country'] == $value['label']) ? 'selected' : '' ?>>
                                            <?php echo $value['label'] ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="field required">
                            <div class="control">
                                <label class="label"><?= $block->escapeHtmlAttr(__('Zip Code')) ?> <span>*</span> </label>
                                <input
                                        type="text"
                                        name="zip_code"
                                        value="<?php echo isset($postedData['zip_code']) ? $postedData['zip_code'] : '' ?>"
                                        data-validate='{"required":true}'
                                        placeholder=""
                                        class="input-text">
                            </div>
                        </div>
                        <div class="field required">
                            <div class="control">
                                <label class="label"><?= $block->escapeHtmlAttr(__('City')) ?> <span>*</span> </label>
                                <input
                                        type="text"
                                        name="city"
                                        value="<?php echo isset($postedData['city']) ? $postedData['city'] : '' ?>"
                                        data-validate='{"required":true}'
                                        placeholder=""
                                        class="input-text">
                            </div>
                        </div>
                        <div class="field required">
                            <div class="control">
                                <label class="label"><?= $block->escapeHtmlAttr(__('Phone')) ?> <span>*</span> </label>
                                <input
                                        id="phone"
                                        type="text"
                                        name="phone"
                                        value="<?php echo isset($postedData['phone']) ? $postedData['phone'] : '' ?>"
                                        data-validate='{"required":true, "validate-number":true}'
                                        placeholder=""
                                        class="input-text">
                            </div>
                        </div>
                        <div class="field required">
                            <div class="control">
                                <label class="label"><?= $block->escapeHtmlAttr(__('Email')) ?> <span>*</span> </label>
                                <input
                                        id="applicant-email"
                                        type="text"
                                        name="email"
                                        value="<?php echo isset($postedData['email']) ? $postedData['email'] : '' ?>"
                                        data-validate='{"required":true, "email":true}'
                                        placeholder=""
                                        class="input-text">
                            </div>
                        </div>
                        <div class="field required">
                            <label class="label"><?= $block->escapeHtml(__('CV')) ?> <span>*</span></label>
                            <div class="control">
                                <div class="fileUpload ">
                                    <input
                                            type="file"
                                            name="cv"
                                            data-validate='{"required":true}'
                                            placeholder=""
                                            class="input-text upload">
                                </div>
                            </div>
                            <p class="fileName"></p>
                        </div>
                        <div class="field required">
                            <label class="label"><?= $block->escapeHtml(__('Personal letter')) ?> <span>*</span></label>
                            <div class="control">
                                <div class="fileUpload ">
                                    <input
                                            type="file"
                                            name="letter"
                                            data-validate='{"required":true}'
                                            placeholder=""
                                            class="input-text upload">
                                </div>
                            </div>
                            <p class="fileName"></p>
                        </div>
                        <div class="submit-form">
                            <button type="submit" class="btn-custom orange-btn">
                                <span><?php echo $block->escapeHtml(__('Send')) ?></span>
                            </button>
                        </div>
                    </form>
                </div>
            <?php else: ?>
                <h2><?php echo __('Sorry,The deadline has crossed'); ?></h2>
            <?php endif; ?>
        <?php else: ?>
            <h2><?php echo __('Sorry. The Job is closed.') ?></h2>
        <?php endif;
    else: ?>
        <h2><?php echo __('Sorry. The Job isn\'t available for current store.'); ?></h2>
    <?php endif; ?>

</div>
