<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post view template
 *
 * @var $block \Magefan\Blog\Block\Post\View
 */
?>
<?php
$_post = $this->getPost();
$_postUrl = $_post->getPostUrl();
$_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<div class="post-view">
    <div class="post-holder post-holder-<?php echo $_post->getId() ?>">
        <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
            <div class="full-width">
                <div class="post-ftimg-hld">
                    <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                </div>
            </div>
        <?php } ?>
        <div class="breadcrumbs">
            <ul class="items">
                <li class="item home">
                    <a href="/" title="Go to Home Page">Home</a>
                </li>
                <li class="item blog">
                    <a href="/blog/" title="Blog">Blog</a>
                </li>
                <li class="item blog_post">
                    <strong><?php echo $_postName ?></strong>
                </li>
            </ul>
        </div>
        <div class="page-title-wrapper">
            <h1 class="page-title">
                <span class="base" data-ui-id="page-title-wrapper"><?php echo $_postName ?></span>
            </h1>
        </div>
        <div class="post-header clearfix">
            <?php echo $this->getInfoHtml() ?>
        </div>

        <div class="post-content">
            <div class="post-description clearfix">
                <div class="post-text-hld">
                    <?php echo $block->getContent() ?>
                    <div class="clear"></div>
                </div>
            </div>
        </div>

        <div class="post-bottom">
            <?php echo $this->getChildHtml('blog.post.bottom') ?>
        </div>

        <div class="post-sharing">
            <div class="post-sharing-text">
                <p><?= /* @escapeNotVerified */ __('Share this post') ?></p>
            </div>
            <div class="addthis_toolbox addthis_default_style addthis_32x32_style" addthis:url="<?php echo $_postUrl ?>">
                <a class="addthis_button_facebook"></a>
                <a class="addthis_button_twitter"></a>
                <a class="addthis_button_email"></a>
                <a class="addthis_button_compact"></a>
            </div>
        </div>
    </div>
</div>
