<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
$_post = $this->getPost();
$_postUrl = $_post->getPostUrl();
$_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<li class="post-holder post-holder-<?php echo $_post->getId() ?>">
    <div class="post-content">
        <div class="post-description">
            <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                <div class="post-ftimg-hld">
                    <div class="post-img-container" style="background-image: url('<?php echo $featuredImage ?>');">
                        <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>"></a>
                    </div>
                </div>
            <?php } ?>
            <div class="post-text-hld">
                <h4 class="post-title">
                    <a class="post-item-link"
                       href="<?php echo $_postUrl ?>">
                        <?php echo $_postName; ?>
                    </a>
                </h4>
                <?php echo $block->getShorContent() ?>
            </div>
        </div>
    </div>
    <div class="post-footer">

    </div>
</li>