<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if ($block->isContentMode() || $block->isMixedMode()): ?>
    <div class="category-cms full-width">
        <div class="category-cms-block">
            <?= $block->getCmsBlockHtml() ?>
        </div>
    </div>
<?php endif; ?>
